server:
  port: 9001
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true

# ?? ?? DB
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(XjEpV7UvEfYBTJWwco+K511OpEWE51sz/pwJ7QxNswgJzN9IliQGH6N/CwsN2vvlz21OCzx0ta07TcMN4xNAFp2uUQb/clTPr0fuCMgkbapcJxZOulE8btVThku6Rpz4jmn+354jL/MPfwd3ynQsZzL2XuLs+O3n)
    username: ENC(TtkK9cJgwIpstcMs/gT5IQ==)
    password: ENC(EWVc3fT+dZWPmqznzHUPIg==)

  messages:
    basename: config/i18n/message, config/i18n/error

  jpa:
    hibernate:
      ddl-auto: update # ?? X (??)
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
        default_batch_fetch_size: 400

  # File ??
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  data:
    redis:
      host: localhost
      port: 6379

  #Spring Security OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(CDOCxjQAelGvNDRHNbgIHcITMMzSo5TtIYXEPu0p6xckxlbdRO23COeEV5C6soquG8dFeMkKGMSnOa7imOJHV1LmanIQA4DKL+08AjXGsNr+v2L7K+BVDg==)
            client-secret: ENC(ehlEfYopWr28y4JcFssFUsJzhno/mlqgCM4MlY+oo3acdluXhOk3bvucaQ7v+yP9)
            scope: profile, email

          naver:
            client-id: ENC(Trc8GyjozbdYrhXz/dH2wR02ZPk48i+bXtZiRx5nibU=)
            client-secret: ENC(UN7P1BPSQDUpqiHcRrNOzV+aXsvbvP32)
            redirect-uri: http://localhost:9000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: ENC(2590a5ZlCL99oTsoc+cPFvxpzsig+e9VBpowEtLitVFPoLLbtyE+51dfSYxPJ+1p)
            client-secret: ENC(SZmkICdyZL2yNRHx8omYwb0Dsvli0uVPLF/ENIFk5xroppKpSOI3qL5s7/SCGrsn)
            redirect-uri: http://localhost:9000/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


# JWT
jwt:
  host: studynook.com
  secret: q1ZST0pl2057VfOGrlBjo6bPcx8L9IZaJx+BtDVHxQpNBS9IKyahbulcV/2mgRzipS/B0AZxEmlBpTDsSi2zxGuRylEwRLpSKo6dlRt3QeFfNwOM4cUet8K0cMvvTTuVe/i6s6VU0KCpCi6kUuEfg4qpyrMD6MQu8DRMOK24eFxnxFJe04L4wpcG3lmFnS/uo0DLx3l4XE94eypYxFLlpQ==
  token-validity-in-milliseconds: 3600000
  refresh-token-validity-in-milliseconds: 12096000

# oauth2 url
oauth:
  redirect-url: http://localhost:8080
  access-token-validity-in-milliseconds: 3600000
  refresh-token-validity-in-milliseconds: 12096000

exclude:
  path :

# Log
logging:
  level:
    root: info
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

jasypt:
  encryptor:
    bean: jasyptStringEncryptor